### ISSUE TITLE
Correções pontuais de gramática

### ISSUE THREAD

**Issue by imfarias** [luszczynski/test-drive-openshift#3]
Prezados,
Identifiquei alguns erros pontuais na gramática e já tomei a liberdade de encaminhar um Pull Request do meu fork com as correções que encontrei durante o treinamento.

Segue URL para o PR: https://github.com/luszczynski/test-drive-openshift/pull/2

Atenciosamente,
Vinicius Farias

**Comment by luszczynski** [comment]
Feito o merge. Obrigado @imfarias.
